baseURL = "https://notes-meetgor-com.vercel.app/"
languageCode = "en-us"
title = "Notes"

[params]
  description = "Technical notes, articles, links and newsletters"
  
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Links"
  url = "/links/"
  weight = 2

[[menu.main]]
  name = "Newsletter"
  url = "/newsletter/"
  weight = 3

[[menu.main]]
  name = "Quotes"
  url = "/quotes/"
  weight = 4

[[menu.main]]
  name = "Thoughts"
  url = "/thoughts/"
  weight = 5

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 6
