baseURL = "https://notes-meetgor-com.vercel.app/"
languageCode = "en-us"
title = "Notes"
theme = "beautifulhugo"
paginate = 10

[outputs]
  home = ["HTML", "JSON"]

[params]
  description = "Technical notes, articles, links and newsletters"
  
[params.author]
  name = "Meet Gor"
  
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Links"
  url = "/links/"
  weight = 2

[[menu.main]]
  name = "Newsletter"
  url = "/newsletter/"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 4
