baseURL = "https://notes-meetgor-com.vercel.app/"
languageCode = "en-us"
title = "Notes"
theme = "terminal"

[params]
  description = "Technical notes, articles, links and newsletters"
  themeColor = "dark"
  showMenuItems = 6

[markup.goldmark.renderer]
  unsafe = true

[params.logo]
  logoText = "Notes"
  logoHomeLink = "/"

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Links"
  url = "/links/"
  weight = 2

[[menu.main]]
   name = "Newsletter"
   url = "/newsletter/"
   weight = 3

[[menu.main]]
   name = "Thoughts"
   url = "/thoughts/"
   weight = 4

[[menu.main]]
   name = "Tags"
   url = "/tags/"
   weight = 5
