[build]
  command = "CGO_ENABLED=0 go build -o netlify/functions/cms ./netlify/functions/cms/main.go"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/cms/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  condition = "!{path}.html"

[context.production]
  environment = { ENV = "production", ADMIN_PASSWORD = "test" }

[context.deploy-preview]
  environment = { ENV = "preview" }

[context.branch-deploy]
  environment = { ENV = "staging" }
