baseURL = "/"
languageCode = "en-us"
title = "Notes"
theme = "stack"
enableGitInfo = true
outputs.home = ["HTML", "JSON"]

[params]
  description = "A collection of technical notes and posts"
  
[params.author]
  name = "Meet Gor"
  email = "me@meetgor.com"

[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true
