baseURL = "/"
languageCode = "en-us"
title = "Notes"
theme = "stack"
enableGitInfo = true

[params]
  description = "A collection of technical notes and posts"
  mainSections = ["posts"]
  
[params.author]
  name = "Meet Gor"
  email = "me@meetgor.com"

[params.homepage]
  profile = false

[params.colorScheme]
  toggle = true
  default = "light"
  
[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 3
