baseURL = "https://notes.meetgor.com/"
languageCode = "en-us"
title = "Notes"
theme = "minimal"
enableGitInfo = true
outputs.home = ["HTML", "JSON"]

[params]
  description = "A collection of technical notes and posts"
  author = "Meet Gor"
  
[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true
