baseURL = "/"
languageCode = "en-us"
title = "Notes"
theme = "stack"
enableGitInfo = true
outputs.home = ["HTML", "JSON"]

[params]
  description = "A collection of technical notes and posts"
  mainSections = ["posts"]
  
[params.author]
  name = "Meet Gor"
  email = "me@meetgor.com"

[params.homepage]
  profile = false

[[params.homepage.social]]
  name = "GitHub"
  url = "https://github.com"
  
[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = -100

[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = -99
