baseURL = "https://example.com/"
languageCode = "en-us"
title = "Blog"
theme = "blog-theme"

[params]
  author = "Author"
  description = "A minimalist blog"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
